[versions]
activity = "1.11.0"
annotation = "1.9.1"
appcompat = "1.7.1"
agp = "8.13.1"
cardview = "1.0.0"
circleimageview = "3.1.0"
constraintlayout = "2.2.1"
glide = "5.0.5"
material = "1.13.0"
recyclerview = "1.4.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }